#!/usr/bin/env ruby
# Script for deploying the package via Travis CI

require 'fileutils'
require 'json'

FileUtils.mkdir_p(File.expand_path('~/.stack/upload'))

File.open(File.expand_path('~/.stack/upload/credentials.json'), 'w') { |f|
  config = {
    :username => ENV['HACKAGE_USERNAME'],
    :password => ENV['HACKAGE_PASSWORD'],
  }
  f.write(config.to_json)
}

exec('stack', 'upload', '.', '--no-signature')
